# Generated by Django 5.2 on 2025-05-11 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коллекции')),
                ('year', models.PositiveIntegerField(verbose_name='Год коллекции')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_page_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='catalog/')),
                ('category', models.CharField(choices=[('all', 'Все товары'), ('bracelets', 'Браслеты'), ('earrings', 'Серьги'), ('pendants', 'Кулоны'), ('necklaces', 'Ожерелья'), ('rings', 'Кольцо')], default='all', max_length=20)),
                ('price', models.IntegerField(verbose_name='Цена (в рублях)')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='main.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/', verbose_name='Фотография')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.collection')),
            ],
        ),
    ]
