# Generated by Django 5.2 on 2025-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='description',
            field=models.TextField(blank=True, help_text='Многострочное описание товара', null=True, verbose_name='Описание'),
        ),
    ]
