# Generated by Django 5.2 on 2025-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catalogitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(default='out of stock', max_length=255, verbose_name='Статус коллекции (наличие)'),
            preserve_default=False,
        ),
    ]
