# Generated by Django 5.2 on 2025-05-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Многострочное описание коллекции', null=True, verbose_name='Описание'),
        ),
    ]
