# Generated by Django 5.2 on 2025-05-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='tags',
            field=models.TextField(blank=True, help_text='Через запятую', null=True, verbose_name='Ключевые слова'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='main.catalogitem')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение товара',
                'verbose_name_plural': 'Дополнительные изображения товаров',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.productimage', verbose_name='Дополнительные изображения'),
        ),
    ]
