# Generated by Django 5.2 on 2025-05-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_collection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='itemImages/', verbose_name='Фотография')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemImages', to='main.catalogitem')),
            ],
        ),
    ]
