# Generated by Django 5.2 on 2025-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='available_sizes',
            field=models.JSONField(blank=True, help_text='Список доступных размеров в формате JSON (например: ["S", "M", "L"])', null=True, verbose_name='Размеры кольца(для колец)'),
        ),
    ]
