# Generated by Django 5.2 on 2025-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_catalogitem_tags_productimage_catalogitem_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/'),
        ),
    ]
